services:
  db:
    container_name: db-tasks-app
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/envs/.env.prod
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: fastapi-tasks-app
    image: ppavlovp/private_images:tasks-app-backend
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    env_file:
      - ./backend/envs/.env.prod
    restart: always
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx-tasks-app
    build:
      context: ./nginx
      dockerfile: prod/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./backend/envs/.env.prod
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend

volumes:
  postgres_data: