services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    env_file:
      - ./backend/envs/.env.prod
    volumes:
      - ./backend/db:/home/app/db/
    user: "ubuntu"
    restart: always
    platform: linux/amd64

  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/prod/conf.d:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend