services:
  db:
    image: postgres:17
    container_name: db-tasks-app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/envs/.env.dev
    ports:
      - "5433:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: fastapi-tasks-app
    env_file:
      - ./backend/envs/.env.prod
    volumes:
      - ./backend/db:/home/app/db/
    user: "ubuntu"
    restart: always
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    container_name: nginx-tasks-app
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend

volumes:
  postgres_data: