services:
  db:
    container_name: db-tasks-app
    image: postgres:17
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/envs/.env.prod
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tasks-network

  backend:
    container_name: fastapi-tasks-app
    image: ppavlovp/private_images:tasks-app-backend
    environment:
      - GUNICORN_WORKERS=2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    env_file:
      - ./backend/envs/.env.prod
    restart: always
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tasks-network

  nginx:
    container_name: nginx-tasks-app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    build:
      context: ./nginx
      dockerfile: prod/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./backend/envs/.env.nginx
    restart: always
    volumes:
      - ./nginx/prod/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend
    networks:
      - tasks-network

volumes:
  postgres_data:

networks:
  tasks-network:
    external: false
    driver: bridge
    name: tasks_management_app_tasks-network