services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    env_file:
      - ./backend/envs/.env.dev
    volumes:
      - ./backend/db:/home/app/db/
    user: "ubuntu"
    restart: always
    platform: linux/amd64

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

networks:
  default:
    driver: bridge