global:
  slack_api_url: ${ALERTMANAGER_SLACK_WEBHOOK}

route:
  receiver: slack-notification
  group_by: ['alertname', 'cluster']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

receivers:
  - name: slack-notification
    slack_configs:
      - channel: '#all-monitoring'
        title: 'Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true