"""Add notification_id field in Task model

Revision ID: 47cd350658c4
Revises: 25b96b78df0a
Create Date: 2025-08-05 13:24:46.999663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cd350658c4'
down_revision: Union[str, Sequence[str], None] = '25b96b78df0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notification_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'notification_id')
    # ### end Alembic commands ###
